#%RAML 1.0
title: MuleSoft IDP Callback API
version: v1
mediaType: application/json
protocols: HTTPS

securitySchemes:
  SecurityScheme-ClientIDEnforcement-queryparam-apikey:
    displayName: Client ID Enforcement Policy via Query Params
    type: Pass Through
    description: |
      ### Adding API Key to Query Parameters

      Use Client ID Enforcement policy with API Manager

      Custom Expression

      Client ID Expression
      DataWeave Expression to be used to extract the Client ID from API requests

            ```
              #[%dw 2.4 import fromBase64 from dw::core::Binaries import * from dw::core::Strings output application/java --- substringBefore(fromBase64(attributes.queryParams.apikey as String), ':')]
            ```

      Client Secret Expression
      DataWeave Expression to be used to extract the Client Secret from API requests

            ```
              #[%dw 2.4 import fromBase64 from dw::core::Binaries import * from dw::core::Strings output application/java --- substringAfter(fromBase64(attributes.queryParams.apikey as String), ':')]
            ```

      Your apikey becomes ClientId:ClientSecret then Base64

    describedBy:
      queryParameters:
        apikey:
          description: Client Id:Client Secret then base64 encoded
          type: string
          example: ODZiZjQxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxY=
      responses:
        "401":
          body:
            application/json:
              properties:
                error:
                  example: Invalid Client
                  type: string
        "500":
          body:
            application/json:
              properties:
                error:
                  example: Bad response from authorization server, or WSDL SOAP Fault error
                  type: string

/idp/callback:
  patch:
    securedBy:
      - SecurityScheme-ClientIDEnforcement-queryparam-apikey
    displayName: IDP patchCallback
    description: |
      Receives callback notifications from MuleSoft IDP when document action execution finishes
      with status SUCCEEDED, FAILED, or MANUAL_VALIDATION_REQUIRED.
    queryParameters:
      apikey:
        description: Base64 encoded ClientId:ClientSecret
        type: string
        required: true
      context:
        description: Miscellaneous to save the context/keys of the origin of the document
        example: Salesforce Case Id
        type: string
        required: false
    body:
      application/json:
        description: IDP Callback Body
        properties:
          executionId:
            description: IDP Execution Id returned after successful submission
            type: string
            required: true
            example: 022c61de-9bfc-4a94-8a9c-43c5f8ac153e
          actionId:
            description: Published Document Action UUID
            type: string
            required: false
            example: 9026458a-868d-40b6-90e0-6e80639e0aea
          version:
            description: Document Action Version
            type: string
            required: false
            example: "1.0.0"
    responses:
      "200":
        body:
          application/json:
            properties:
              correlationId:
                example: 22e79d23-f1f8-49e4-a542-644c55548141
                type: string
      "401":
        description: Unauthorized - Invalid API Key
      "500":
        description: Internal Server Error
